name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git and rebase from remote
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout main
          git rebase origin/main

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit awake: $(date -u)" || echo "Nothing to commit"

      - name: Push commit
        run: |
          git push origin main
