name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for rebase/push

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set remote and sync with origin/main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout main
          git reset --hard origin/main  # <- force sync

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit awake: $(date -u)" || echo "Nothing to commit"

      - name: Push to main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
