name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full git history is required for rebase

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set authenticated remote
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git

      - name: Pull, commit, and push
        run: |
          git pull --rebase origin main
          git commit --allow-empty -m "Keep Streamlit awake: $(date -u)" || echo "Nothing to commit"
          git push origin HEAD:main

        run: |
          git push origin HEAD:main
