name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with remote and set upstream
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git checkout main
          git fetch origin
          git pull --rebase origin main  # Ensure latest changes are fetched and rebased
          git branch --set-upstream-to=origin/main main

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit awake: $(date -u)" || echo "Nothing to commit"

      - name: Push commit
        run: |
          git push origin main || (git pull --rebase origin main && git push origin main)  # Retry push after rebase if it fails
