name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit awake"
          git push
